apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: special-capybara-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: special-capybara-nodejs 
  name: special-capybara-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: special-capybara-nodejs 
